### ISSUE TITLE
Link to WIKI not working

### ISSUE THREAD

**Issue by siemvaessen** [unhcr/psr.js#1]
The provided link to the WIKI (http://popdata.unhcr.org/wiki/index.php/API_Documentation) renders a 404..

**Comment by benrudolph** [comment]
i believe this is the new one: http://popdata.unhcr.org/wiki/index.php?title=API_Documentation

this repo is completely abandoned by the way

**Comment by siemvaessen** [comment]
ah ok. will change it to the correct URI anyway. What is the in use API now then?

**Comment by lpitoiset** [comment]
both website and api were put on hold until we release a new version later this week - for Refugee Day -.
In the meantime I would recommend you to check data.unhcr.org/wiki to see if you can find the data you are looking for
